- json/linea-mainnet-token-shortlist.json
Action: create mainnet token list
Context / rational: mainnet has been launched
PR checklist:
> Add mainnet file

- json/linea-goerli-token-shortlist.json
- json/linea-mainnet-token-shortlist.json
Action: update metadata config
Context / rational: repo has been made public
PR checklist:
-> still v0
> Change testnet token list

- json/linea-mainnet-token-shortlist.json
Action: add
Context / rational: Adding first tokens supported by Linea bridge
PR checklist:
> Add USDC and WBTC

- json/linea-mainnet-token-shortlist.json
Action: add
Context / rational: new tokens supported by the bridge
PR checklist:
> Add tokens 2023 08 08

- json/linea-mainnet-token-shortlist.json
Action: add
Context / rational: add wstETH
PR checklist:
> add wstETH

- .husky/pre-commit
- json/linea-mainnet-token-shortlist.json
> Adding GNO and USDP

- json/linea-goerli-token-shortlist.json
Add goerli WETH address
PR checklist:
> fix: WETH goerli address

- .github/workflows/sync-mainnet-fulllist.yml
- .github/workflows/verify-and-test.yml
> fix: script config loading

- json/linea-goerli-token-shortlist.json
> Fix l2 USDC Goerli address

- json/linea-goerli-token-shortlist.json
Action: 
Fix Linea USDC L2 address
> Fix usdc linea address

- .github/workflows/sync-mainnet-fulllist.yml
- README.md
- index.html
- json/linea-mainnet-token-fulllist.json
- public/script.js
- src/services/token.service.ts
Action: 
- PR merging is not happening because it needs approval.
- Action a GitHub action setup to do so.
- Fix GitHub page dark theme
> fix: add auto approve

- public/script.js
Action: 
fix Ethereum link to Etherscan
> fix: etherscan link

- .github/workflows/sync-mainnet-fulllist.yml
Action: 
change cron from every hour to every day at 12:00
> feat: everyday at noon

- json/linea-mainnet-token-fulllist.json
- json/linea-mainnet-token-shortlist.json
PR checklist:
- [✅] I've kept the token list in alphabetical order based on token symbol
- [✅] I've updated the `updatedAt` (and potentially `createdAt`) fields
- [✅] I've update the list version number as per README instruction
> Overnight usd+/usdt+

- json/linea-mainnet-token-fulllist.json
> added lube token to fulllist

- json/linea-mainnet-token-fulllist.json
- json/linea-mainnet-token-shortlist.json
> Added USK Token

- json/linea-mainnet-token-fulllist.json
- json/linea-mainnet-token-shortlist.json
Action: add token
USDLR is a fiat-backed stablecoin that pays DeFi protocols. We're working with several top DEXes on Linea.
PR checklist:
> feat: USDLR

- json/linea-mainnet-token-shortlist.json
Action: add xmt token
PR checklist:
> added XMT token

- json/linea-mainnet-token-fulllist.json
- json/linea-mainnet-token-shortlist.json
> feat: add GRAI token

- json/linea-mainnet-token-shortlist.json
> Feat: A3A token - Short list

- json/linea-mainnet-token-shortlist.json
- src/services/token.service.ts
> Feat: add uniETH, LYNX, Foxy, MENDI, sMendi, uMendi and NILE tokens to mainnet short list

- json/linea-sepolia-token-shortlist.json
Action: add token
PR checklist:
> Add USDC and WETH to the Sepolia tokenlist

- json/linea-mainnet-token-fulllist.json
- json/linea-mainnet-token-shortlist.json
> Add LVC,veLVC

- json/linea-mainnet-token-shortlist.json
> Added ZeroLend to linea-mainnet-token-shortlist.json

- json/linea-mainnet-token-shortlist.json
Action: add token
Context / rational: CROAK is a new memecoin on Linea created by Efrogs.
PR checklist:
> feat: add CROAK to the token shortlist

- json/linea-mainnet-token-shortlist.json
PR checklist:
- [c] I've verified and published the contract source
- [c] I've kept the token list in alphabetical order based on token symbol
- [c] I've updated the `updatedAt` (and potentially `createdAt`) fields
- [c] I've updated the list version number as per README instruction
> Add The Nemesis (NEMS) to the token list

- json/linea-mainnet-token-shortlist.json
* feat: add nems canonical-bridge token
* fixup: 1 - feat: add nems canonical-bridge token
* fixup: 2 - feat: add nems canonical-bridge token
PR checklist:
> fixup: 139 - Add The Nemesis (NEMS) to the token list (#176)

- json/linea-mainnet-token-shortlist.json
> ref: bump updatedAt at shortlit-file level

- json/linea-mainnet-token-shortlist.json
- json/linea-sepolia-token-shortlist.json
Action: update token USDC
Context / rational: Update new token address for USDC on Linea Sepolia.
PR checklist:
> feat: update new USDC token on Linea sepolia

- json/linea-mainnet-token-shortlist.json
Action: add
Context / rational: we have created a memecoin which is doing quite well and Christopher advised me to add the token here to enable tracking in the metamask wallet. We are already listed on coingecko for price tracking.
PR checklist:
> Add Linpuss token to Linea token shortlist

- json/linea-mainnet-token-shortlist.json
Action: add token 
Context / rational: add DERI to the shortlist
PR checklist:
> Add DERI to linea-mainnet-token-shortlist.json

- json/linea-mainnet-token-fulllist.json
- json/linea-mainnet-token-shortlist.json
> Update Deri Protocol on shortlist and fulllist

- json/linea-mainnet-token-shortlist.json
Action: update 
Context / rationale:
PR checklist:
> fix: mainnet token shortlist formatting issue

- json/linea-mainnet-token-shortlist.json
Action: add LUSD Stablecoin
Context / rationale:
PR checklist:
> feat: added Liquity's LUSD Stablecoin

- json/linea-mainnet-token-shortlist.json
Action: add token
Context / rationale:
PR checklist:
> feat: add BOL

- json/linea-mainnet-token-shortlist.json
- json/templates/linea-sepolia-token-version-template.json
**Action:** add / update / remove token (keep those that apply)  
**Context / Rationale:**
---
> feat: add BEAVER

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/validate-json.yml
- .github/workflows/verify-json.yml
- json/linea-mainnet-token-shortlist.json
**Action:** refactoring of the CI pipelines
**Context / Rationale:** avoid permissioned CI on PR
---
> chore: refactor CI pipelines

- .husky/pre-commit
- json/linea-mainnet-token-shortlist.json
**Action:** Update
**Context / Rationale:**
Fixes formatting
---
> [Fix] prettier fix for token short list
